name: Build and publish

on:
  push: 
    branches: 
      - main

jobs:
  build-and-publish:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@infinitaslearning'

      - run: npm ci
      - run: git config --global user.email "github@infinitaslearning.com"
      - run: git config --global user.name "Infinitas Learning"
      - run: npm version `npm pkg get version | tr -d '"' | cut -d '.' -f 1-2`.${{ github.run_number }}
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

